n1=int(input('Digite um número para ver sua tabuada: '))

print('-----------')
print('{} x 1 = {}'.format(n1, n1))
print('{} x 2 = {}'.format(n1, (n1*2)))
print('{} x 3 = {}'.format(n1, (n1*3)))
print('{} x 3 = {}'.format(n1, (n1*4)))
print('{} x 3 = {}'.format(n1, (n1*5)))
print('{} x 3 = {}'.format(n1, (n1*6)))
print('{} x 3 = {}'.format(n1, (n1*7)))
print('{} x 3 = {}'.format(n1, (n1*8)))
print('{} x 3 = {}'.format(n1, (n1*9)))
print('{} x 3 = {}'.format(n1, (n1*10)))
print('-----------')
